### ISSUE TITLE
Problems to run the benchmark.py

### ISSUE THREAD

**Issue by lesleyhaha** [BerkeleyAutomation/sd-maskrcnn#11]
Hi, thanks for your sharing! But I met some problem when run the `python tools/benchmark,py`. My environment is anaconda python3.5, tensorflow-gpu-1.2.0. Here I met the problem is : 
```
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Using TensorFlow backend.
Traceback (most recent call last):
  File "tools/benchmark.py", line 24, in <module>
    from sd_maskrcnn.dataset import ImageDataset
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/lesleybinglei/anaconda3/envs/pthon35/lib/python3.5/site-packages/sd_maskrcnn-0.1.0-py3.5.egg/sd_maskrcnn/dataset.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/lesleybinglei/anaconda3/envs/pthon35/lib/python3.5/site-packages/mask_rcnn-2.1-py3.5.egg/mrcnn/model.py", line 31, in <module>
AssertionError
```

I really need your help! Thanks a lot!

**Comment by mjd3** [comment]
@lesleyhaha your error is coming from these lines:
```
# Requires TensorFlow 1.3+ and Keras 2.0.8+.
from distutils.version import LooseVersion
assert LooseVersion(tf.__version__) >= LooseVersion("1.3")
assert LooseVersion(keras.__version__) >= LooseVersion('2.0.8')
```
As you can see, the Mask RCNN submodule requires that you have at least TensorFlow version 1.3 and Keras version 2.0.8. Is there a reason you need TensorFlow 1.2.0? You can solve this problem by updating to a newer TensorFlow version.

**Comment by mjd3** [comment]
@lesleyhaha Were you able to resolve this issue?
